/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PortalRouteImport } from './routes/portal/route'
import { Route as AuthenticationRouteImport } from './routes/_authentication/route'
import { Route as IndexImport } from './routes/index'
import { Route as PortalIndexImport } from './routes/portal/index'
import { Route as PortalServicesImport } from './routes/portal/services'
import { Route as AuthenticationRegisterImport } from './routes/_authentication/register'
import { Route as AuthenticationLoginImport } from './routes/_authentication/login'

// Create/Update Routes

const PortalRouteRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticationRouteRoute = AuthenticationRouteImport.update({
  id: '/_authentication',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PortalIndexRoute = PortalIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRouteRoute,
} as any)

const PortalServicesRoute = PortalServicesImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => PortalRouteRoute,
} as any)

const AuthenticationRegisterRoute = AuthenticationRegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthenticationRouteRoute,
} as any)

const AuthenticationLoginRoute = AuthenticationLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthenticationRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authentication': {
      id: '/_authentication'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticationRouteImport
      parentRoute: typeof rootRoute
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRoute
    }
    '/_authentication/login': {
      id: '/_authentication/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthenticationLoginImport
      parentRoute: typeof AuthenticationRouteImport
    }
    '/_authentication/register': {
      id: '/_authentication/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthenticationRegisterImport
      parentRoute: typeof AuthenticationRouteImport
    }
    '/portal/services': {
      id: '/portal/services'
      path: '/services'
      fullPath: '/portal/services'
      preLoaderRoute: typeof PortalServicesImport
      parentRoute: typeof PortalRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexImport
      parentRoute: typeof PortalRouteImport
    }
  }
}

// Create and export the route tree

interface AuthenticationRouteRouteChildren {
  AuthenticationLoginRoute: typeof AuthenticationLoginRoute
  AuthenticationRegisterRoute: typeof AuthenticationRegisterRoute
}

const AuthenticationRouteRouteChildren: AuthenticationRouteRouteChildren = {
  AuthenticationLoginRoute: AuthenticationLoginRoute,
  AuthenticationRegisterRoute: AuthenticationRegisterRoute,
}

const AuthenticationRouteRouteWithChildren =
  AuthenticationRouteRoute._addFileChildren(AuthenticationRouteRouteChildren)

interface PortalRouteRouteChildren {
  PortalServicesRoute: typeof PortalServicesRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteRouteChildren: PortalRouteRouteChildren = {
  PortalServicesRoute: PortalServicesRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteRouteWithChildren = PortalRouteRoute._addFileChildren(
  PortalRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticationRouteRouteWithChildren
  '/portal': typeof PortalRouteRouteWithChildren
  '/login': typeof AuthenticationLoginRoute
  '/register': typeof AuthenticationRegisterRoute
  '/portal/services': typeof PortalServicesRoute
  '/portal/': typeof PortalIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticationRouteRouteWithChildren
  '/login': typeof AuthenticationLoginRoute
  '/register': typeof AuthenticationRegisterRoute
  '/portal/services': typeof PortalServicesRoute
  '/portal': typeof PortalIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authentication': typeof AuthenticationRouteRouteWithChildren
  '/portal': typeof PortalRouteRouteWithChildren
  '/_authentication/login': typeof AuthenticationLoginRoute
  '/_authentication/register': typeof AuthenticationRegisterRoute
  '/portal/services': typeof PortalServicesRoute
  '/portal/': typeof PortalIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/portal'
    | '/login'
    | '/register'
    | '/portal/services'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/login' | '/register' | '/portal/services' | '/portal'
  id:
    | '__root__'
    | '/'
    | '/_authentication'
    | '/portal'
    | '/_authentication/login'
    | '/_authentication/register'
    | '/portal/services'
    | '/portal/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticationRouteRoute: typeof AuthenticationRouteRouteWithChildren
  PortalRouteRoute: typeof PortalRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticationRouteRoute: AuthenticationRouteRouteWithChildren,
  PortalRouteRoute: PortalRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authentication",
        "/portal"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authentication": {
      "filePath": "_authentication/route.tsx",
      "children": [
        "/_authentication/login",
        "/_authentication/register"
      ]
    },
    "/portal": {
      "filePath": "portal/route.tsx",
      "children": [
        "/portal/services",
        "/portal/"
      ]
    },
    "/_authentication/login": {
      "filePath": "_authentication/login.tsx",
      "parent": "/_authentication"
    },
    "/_authentication/register": {
      "filePath": "_authentication/register.tsx",
      "parent": "/_authentication"
    },
    "/portal/services": {
      "filePath": "portal/services.tsx",
      "parent": "/portal"
    },
    "/portal/": {
      "filePath": "portal/index.tsx",
      "parent": "/portal"
    }
  }
}
ROUTE_MANIFEST_END */
